### PR TITLE
Improve card component

### LINKED ISSUE #124: improve card component

### PR DESCRIPTION
**Pull request by yuqi88**
- Renaming the component name
- Update style: Remove unnecessary words (difficulty:) on the puzzle card

close #124

### CODE REVIEW

**Review by Opeyem1a — APPROVED** [review]

**Review by ketphan02 — CHANGES_REQUESTED** [review]
do not delete `package-lock.json`

**Comment by yuqi88** [comment]
@ketphan02 I didn't delete `package-lock.json`.

**Comment by Opeyem1a** [comment]
Oh wait I thought that was weird yeah, package-lock is deleted in this branch somehow

**Comment by yuqi88** [comment]
@Opeyem1a I did, but there are no differences. 
I think the result comes from me being dumb. I accidentally went on a branch we used the last term, and npm install it. Then, I saved it, so there's a diff.

**Comment by Opeyem1a** [comment]
I'm still concerned, since 11k line changes when comparing this branch to main seems weird regardless

**Comment by Opeyem1a** [comment]
Oh I managed to fix it, I think your npm version might be too old @yuqi88 
For reference, I'm on npm 8.1.2 (you can check with `npm --version`)

**Comment by yuqi88** [comment]
aye! 

- Opened an issue & edited the comment on the top of this PR.

**Pull request merged**
