### PR TITLE
Add 404 page

### PR DESCRIPTION
**Pull request by ketphan02**

### CODE REVIEW

**Review by Opeyem1a — CHANGES_REQUESTED** [review]
It generally looks solid to me for now (the error display might need to have more props in the future for redirects, extra info and whatnot) -- Could you add some screenshots to the PR so we can do a quick visual pass on it before merging?

**Comment by ketphan02** [comment]
Sure
image

**Comment by ketphan02** [comment]
Yeah I was thinking that too, I think we need a button to redirect to the landing page

**Review by MtheDV — CHANGES_REQUESTED** [review]
Based on the screenshot: I think we could have the app image at the top, then underneath it show the 404 error with the quote. Then later we can add stuff, but for now that would be good.

**Comment by ketphan02** [comment]
image
This looks better than the last time ngl

**Review by Opeyem1a — APPROVED** [review]

**Pull request merged**
